# Mamba environment file.
name: names
channels:
  - conda-forge
dependencies:
  # Match Lambda runtime's Python version.
  - python=3.12
  # Version 20 is active LTS: https://nodejs.org/en/about/previous-releases.
  - nodejs=20
