[project]
name = "names"
version = "0.2.0"
description = "Generate deterministic duplicate-free mnemonic names"
readme = "README.md"
authors = [
    { name = "eidorb", email = "brodieface@gmail.com" }
]
license = "AGPL-3.0-or-later"
requires-python = ">=3.10"

[dependency-groups]
dev = [
    "aws-cdk-cli>=2.1141.0",
    "aws-cdk-lib>=2.269.0",
    "marimo>=0.24.1",
    "ruff>=0.16.7",
]
