on:
  release:
    types:
      - published
# Do not attempt concurrent runs.
concurrency:
  group: ${{ github.workflow }}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - id: cache
        uses: actions/cache@v4
        # Keep uv cache and Python virtual environment.
        with:
          key: ${{ hashFiles('pyproject.toml', 'uv.lock') }}
          path: |
            ~/.local/share/uv
            .venv
      - run: |
          # Run tests.
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv python pin ${{ matrix.python-version }}
          uv run pytest
  publish:
    runs-on: ubuntu-latest
    permissions:
      # Allows JWT to be requested from GitHub's OIDC provider.
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - id: cache
        uses: actions/cache@v4
        # Keep uv cache and Python virtual environment.
        with:
          key: ${{ hashFiles('pyproject.toml', 'uv.lock') }}
          path: |
            ~/.local/share/uv
            .venv
      - run: |
          # Build.
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv build
      # Only publish if releasing.
      - if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@v1.12.2
