on:
  push:
    branches:
      - main
# Do not attempt concurrent deployments.
concurrency:
  group: ${{ github.workflow }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: cache
        uses: actions/cache@v4
        # Keep uv cache and Python virtual environment
        with:
          key: ${{ hashFiles('.python-version', 'uv.lock') }}
          path: |
            ~/.local/share/uv
            .venv
      - run: |
          # Run tests.
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv run pytest

          # Demo output.
          set -x
          uv run -m names --help
          uv run -m names "${{ github.run_id }}" --count 10 --offset 1000 --format python
      - run: |
          # Say something deep, dawg!
          set -x
          uvx llm install llm-grok
          echo "write the most insightful and terse poem you can about the difficulties of " \
               "naming things using these words (be sure to include a valid http url link):\n" \
               "$(uv run -m names ${{ github.run_id }})" \
            | uvx llm -m grok-beta
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
