on:
  push:
    branches:
      - main
# Do not attempt concurrent deployments.
concurrency:
  group: ${{ github.workflow }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: cache
        uses: actions/cache@v4
        # Keep uv cache and Python virtual environment
        with:
          key: ${{ hashFiles('.python-version', 'uv.lock') }}
          path: |
            ~/.local/share/uv
            .venv
      - run: |
          # Run tests.
          set -x
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv run pytest

          # Demo output.
          uv run -m names --help
          uv run -m names --seed "${{ github.run_id }}"
